### ISSUE TITLE
Collections and LiveSets

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1418]
**User Story**

As a browser developer using loopbacks new realtime sync feature, I should be able to create a collection pointing at a `PersistedModel`. Using this collection I should be able to create a `LiveSet`, or a readable view of a subset of persisted models kept up to date as the data is modified in its data source.

```js
var collection = new Collection(options); // must include path to the PersistedModel
var set = connection.find({live: true, where: ...});
```

**TODO**
 - [x] create module
 - [x] write unit tests
 - [x] write integration tests
 - [x] write basic example
 - [x] depends on `PersistedModel.createChangeStream()`
