### ISSUE TITLE
Consolidate example apps

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1758]
Some of the [topic-specific](https://github.com/strongloop/loopback-example#topic-specific-examples) example apps can be combined with the [tutorial examples](https://github.com/strongloop/loopback-example#tutorials) because they are closely related.  This should be relatively straight-forward.

Here are some candidates
- [x] Fold [loopback-example-embedded-relations](https://github.com/strongloop/loopback-example-embedded-relations) into [loopback-example-relations](https://github.com/strongloop/loopback-example-relations): <br/>**See https://github.com/strongloop/loopback-example-relations/issues/17**
- [x] Fold [loopback-example-passport](https://github.com/strongloop/loopback-example-passport) into [loopback-example-user-management](https://github.com/strongloop/loopback-example-user-management)<br/> **See https://github.com/strongloop/loopback-example-user-management/issues/25**
- [x] Fold [loopback-example-email](https://github.com/strongloop/loopback-example-email) into [loopback-example-app-logic](https://github.com/strongloop/loopback-example-app-logic): <br/> **See https://github.com/strongloop/loopback-example-app-logic/issues/11**

**Comment by crandmck** [comment]
Related: move examples out of component repos into separate example repos:
- https://github.com/strongloop/loopback-component-push/issues/49
- https://github.com/strongloop/loopback-component-storage/issues/26

**Comment by superkhau** [comment]
- [ ]  Merge 5 database branches into one master branch with README steps differing for connectors

**Comment by superkhau** [comment]
@cranmck We can split these tasks out to TO members individually instead now.

**Comment by crandmck** [comment]
ok shall i do that @superkhau ?

**Comment by superkhau** [comment]
yes pls.

**Comment by superkhau** [comment]
How many of these are done? I assume we should go through this list at some point.

**Comment by crandmck** [comment]
I'll review ASAP.

**Comment by crandmck** [comment]
Current status is:
- One of the tasks is done (checked above).
- Open PR: https://github.com/strongloop/loopback-example-relations/pull/20 which looks pretty close to being resolved.  Janny/Simon
- https://github.com/strongloop/loopback-example-user-management/issues/25 is assigned to @richardpringle and has not been started AFAICT.

**Comment by superkhau** [comment]
TY for the status update. Keep chugging along.

**Comment by superkhau** [comment]
Do not fold loopback-example-passport and loopback-example-user-management anymore. They should be updated independently.

**Comment by richardpringle** [comment]
@superkhau, noted, thanks!

**Comment by superkhau** [comment]
@richardpringle FYI, I updated repo experts, you are now responsible for `loopback-example-storage` as I moved the examples from `loopback-component-storage` there just now.

@crandmck I'm moved the examples from component storage to loopback-example storage, please do what you need to and update your references. I will update loopback-example.

As far as I'm concerned, all the items in this issue are taken care of. Closing.
