### ISSUE TITLE
New functionalities: replaceAttributes and replaceOrCreate

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback#1876]
### Goal:
Adding support for  the following:

Related spike task: https://github.com/strongloop-internal/scrum-loopback/issues/621

###### Description:
Replace the model instance with a single attribute. Equivalent to `replaceAttributes({name: 'value'}, cb)`
###### Example:
If you have this model instance `{ name: 'foo', surname: 'bar', age: 20}`
`replaceAttribute('name', 'baz', cb} -> { name: 'baz'}`

###### Description:
Replaces set of attributes.
###### Example:
If you have this model instance `{ name: 'foo', surname: 'bar', age: 20}`
`replaceAttributes({'name': 'baz', 'age': 21}, cb) -> { name: 'baz', age: 21}`

##### PersistedModel.replaceOrCreate(data, callback)
Replace or create a model instance.

###  API Design:
We would like to know what is the opinion in the community in terms of HTTP methods and endpoints to use for these new functionalities. Here I'm quoting Miroslav's opinion in this regard:

> ATM, PUT /mymodels calls updateOrCreate
a more appropriate semantics would be to map updateOrCreate to PATCH /mymodels and map replaceOrCreate to PUT /mymodels
however, that's a big breaking change
I'm not sure how people will like it
I guess we could provide a flag to enable the old 2.x-like behaviour

Please Let us know how you would like these new functionalities to be exposed as API endpoints.

Here is the checKlist of the work:

###### Implementing replaceAttribute/replaceAttributes for relational databases (connect to https://github.com/strongloop-internal/scrum-loopback/issues/646):
- [x] Implementing replaceAttribute/replaceAttributes for MySQL (atomic)
- [x] Implementing replaceAttribute/replaceAttributes for Oracle
- [x] Implementing replaceAttribute/replaceAttributes for Postgres 
- [x] Implementing replaceAttribute/replaceAttributes for SQL Server 

###### Implementing replaceOrCreate for relational databases (connect to https://github.com/strongloop-internal/scrum-loopback/issues/658):
- [x] Implementing replaceOrCreate for MySQL (atomic)
- [x] Implementing replaceOrCreate for Oracle 
- [x] Implementing replaceOrCreate for Postgres 
- [x] Implementing replaceOrCreate for SQL Server

###### Implementing replaceAttribute/replaceAttributes for NoSQL database (MongoDB) (connect to https://github.com/strongloop-internal/scrum-loopback/issues/659):
- [x] Implementing replaceAttribute/replaceAttributes for mongodb

###### Implementing replaceOrCreate for NoSQL database (MongoDB) (connect to https://github.com/strongloop-internal/scrum-loopback/issues/660):
- [x] Implementing replaceOrCreate for mongodb

###### Adding support in loopback-datasource-juggler 
- [x] Implementing replaceAttribute/replaceAttributes for loopback-datasource-juggler (connect to https://github.com/strongloop-internal/scrum-loopback/issues/661)
- [x] Implementing replaceOrCreate for loopback-datasource-juggler(connect to https://github.com/strongloop-internal/scrum-loopback/issues/666)

###### Extra
- [ ] Desicion on API design and exposing the functionalities as RESTfull API endpoints for replaceOrCreate and replaceAttributes (connetc to https://github.com/strongloop-internal/scrum-loopback/issues/662)
- [x] Implemeting replaceAttribute(s) and replaceOrCreate for memory connector (connect to https://github.com/strongloop-internal/scrum-loopback/issues/663)

Thanks
@bajtos @ritch @raymondfeng @superkhau

**Comment by alFReD-NSH** [comment]
Out of curiosity I have two questions, I'm trying to understand the future changes.

What's the difference between `[updateAttributes](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes)` and `replaceAttributes`?

And other than MySQL why for other SQL databases it would be non-atomic? I thought `replaceAttributes` should just be a update in SQL, which should be atomic.

**Comment by bajtos** [comment]
@alFReD-NSH thanks for chiming in!

> What's the difference between `updateAttributes` and `replaceAttributes`?

Consider a `Car` model instance `{ maker: "Skoda", model: "Superb", year: "2015" }`.

```js
var inst = // get the car instance from the db
inst.unsetAttribute('year');

inst.updateAttributes(inst);
// oops, year was not deleted
// { maker: "Skoda", model: "Superb", year: "2015" }

inst.replaceAttributes(inst);
// year was deleted now
// { maker: "Skoda", model: "Superb" }
```

In other words, there was no reliable way how to unset a property/attribute/column in a database once it was set. There is a workaround of setting the property to `null`, which is ok for relational (SQL) databases, because SQL does not distinguish between `null` and `undefined`; but it's not great for NoSQL databases like MongoDB.

> And other than MySQL why for other SQL databases it would be non-atomic? I thought replaceAttributes should just be a update in SQL, which should be atomic.

I think that's a typo. `replaceAttributes` will be always atomic. It's `replaceOrCreate` that needs special support in connector in order to work in an atomic way.

**Comment by bajtos** [comment]
@alFReD-NSH here is another issue with the current implementation: we expose `updateAttributes` as `PUT /api/models/:id`, which is rather misleading, as `PUT` is expected to replace the whole instance, not only patch specified arguments. So eventually `PUT` should call `replaceAttributes` (or `replaceById`) and `updateAttributes` (or `patchById`) should be remapped to `PATCH`.

**Comment by richardpringle** [comment]
@bajtos, @Amir-61, when making this change, we need to make sure that `PUT /myModels` can take an array of models. It looks like we are missing a test-case for this.

see issue #2123

**Comment by Amir-61** [comment]
@richardpringle @bajtos 

>@bajtos, @Amir-61, when making this change, we need to make sure that PUT /myModels can take an array of models. It looks like we are missing a test-case for this.
see issue #2123

We have never had support for bulk update; we have just had support for bulk insert; the issue you mentioned should be labeled as a feature not a bug.

Thanks!

**Comment by richardpringle** [comment]
@Amir-61, I disagree. All of the other CRUD operations that happen at the class level (vs the instance level) accept an array of model instances. It is an inconsistency and thus I have labelled it a bug. 

If we are making a design change, all aspects of the design should be considered. Just because we had not supported a bulk update before does not mean that we should simply ignore it again. As a LoopBack user, I expect consistency.

My suggestion: add support for bulk-update with `updateOrCreate` and add the patch onto LoopBack 2 and make the change of the endpoint mapping to `replaceOrCreate` in LoopBack 3 that follows that same functionality.

**Comment by richardpringle** [comment]
Just to add:

Trying to do a bulk update throws an "unkown error". If this were a feature, we would be passing back a meaningful error message. 

Also, there is a documentation issue [here](https://apidocs.strongloop.com/loopback/#persistedmodel-upsert). The first input parameter `data` is described as a model instance. The function however can take an array of model instances. The documentation is inconsistent with [create](https://apidocs.strongloop.com/loopback/#persistedmodel-create) even though the method can take the same parameters as `create`. 

In any case, when we have a static method named "create", I would expect similar arguments in another static method called "<alternative>OrCreate", be it "replace" or "update". If we don't wish to support a bulk `replaceOrCreate`, I think that the method name should be changed. In the case of `updateOrCreate`, I think it is too late to change the naming convention, but I believe that the design should be improved before we release anything.

**Comment by bajtos** [comment]
@richardpringle from my experience, supporting both single-instance and bulk update in the same method is cumbersome for several reasons:
 - The type of output argument(s) depends on the type of the input argument(s) - array vs. object - which is difficult to encode in Swagger. In our AngularJS SDK, we had to create a wrapper method `createMany` to handle the array case.
 - Error handling is very cumbersome, especially when using promises. The current implementation of batch create simply calls regular create for each array item. It is possible that some of the items are created while some other items were not created because of an error. This leaves the database in rather weird state - some records were created, some weren't, it's not clear how to revert (roll back) the items not created, it's not clear how to signal back the result of the operation - was it a success? was it an error?
 - The implementation of `replaceById` and `replaceOrCreate` is dragging for too long, we need to wrap it up at some reasonable feature set and move on.

However, I agree with you that inconsistency is bad for LoopBack users.

I am proposing to fix both `updateOrCreate` and `replaceOrCreate` to report a meaningful error when the `data` argument is an array (2.x, 3.0). That should prevent user confusion.

In the future, we can implement batch operations (create, update, replace) that work atomically, with the support from connectors. That's a lot of work though, and IMO it's not a priority right now. I think the batch variants should use a different method name, e.g. `createMany`, `updateOrCreateMany` and `replaceOrCreateMany` to make it clear they accept and return an array.

**Comment by richardpringle** [comment]
@bajtos, we have `PersistedModel.createUpdates` and `PersistedModel.bulkUpdate` functions, I thought we could use those but I see that they are not in `dao.js` (in persisted-model.js in loopback-core).

**Comment by bajtos** [comment]
> we have `PersistedModel.createUpdates` and `PersistedModel.bulkUpdate` functions, which is why I suggested supporting the functionality at the `/MyModels` endpoint. I thought we could use those but I see that they are not in `dao.js` (in persisted-model.js in loopback-core).

Those two methods were designed for use for change replication. However, I like the idea of having a more generic variant of `bulkUpdate` that could be used on its own to perform a set of updates (create/replace/delete) in one batch. OTOH, to implement it correctly with atomic semantics, we will face the same difficulties as described in my previous comment :(

**Comment by sonalisa1** [comment]
Is there a method to perform updateOrCreate with Where clause ?

**Comment by richardpringle** [comment]
@Amir-61, you want to answer that one? ^

**Comment by Amir-61** [comment]
>Is there a method to perform updateOrCreate with Where clause ?
I personally don’t think if `where` clause makes sense with the essence of `updateOrCreate`, on the other hand it does make sense for `update`, for which we already have support. Lets see how `updateOrCreate` / `upsert` works… if the `data` object  you pass has the PK and there is already an instance with that PK, the operation would be `update`, otherwise the operation would be `create`.  Hence, everything is based on the `data` object you pass if there is already an instance with that PK it would be update, otherwise `create`. I don’t think if you can fit `where` clause for `updateOrCreate`. unless I’m missing what you are proposing…

CC: @bajtos

**Comment by sonalisa1** [comment]
Hi..I have a requirement to perform upsert with a foreign key like in case of salesforce connector.Upsert where foreign key = <value>.

**Comment by Amir-61** [comment]
Hey @sonalisa1,

Hi..I have a requirement to perform upsert with a foreign key like in case of salesforce connector.Upsert where foreign key=value

@bajtos could give more info about our future plans. Also, it is worth mentioning we welcome community contributions. If you like to contribute, please send a patch and ping me in your PR, so I'll make sure it gets landed as soon as possible. 

Thanks!

**Comment by bajtos** [comment]
> Is there a method to perform updateOrCreate with Where clause ?

We don't have such method, although we have `findOrCreate` which implements the part where a new model is created when not found. @sonalisa1 please open a new github issue to keep track of your feature request.

**Comment by richardpringle** [comment]
@Amir-61 :tada:
