### ISSUE TITLE
Stream the http response

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#213]
Consider a remotable method that returns a stream as the result, for example "download file" in loopback-storage-service ([source](https://github.com/strongloop/loopback-storage-service/blob/64f3f6964413925746de366a7d49d566ed84b92c/lib/storage-handler.js#L114)).

The current implementation takes the response object as an argument and does not call the provided callback. This means that "after" hooks are never called. ([remoting metadata](https://github.com/strongloop/loopback-storage-service/blob/64f3f6964413925746de366a7d49d566ed84b92c/lib/storage-service.js#L200-L207)).

```js
File.download = function(file, res, cb) {
  var reader = fs.createReadStream('storage/' + file);
  reader.on('error', function (err) {
    res.type('application/json');
    res.send(500, { error: err });
  });
  reader.pipe(res);
  // callback is intentionally not invoked
};

File.remoteMethod('download', {
  accepts: [
    {arg: 'file', type: 'string', 'http': {source: 'path'}},
    {arg: 'res', type: 'object', 'http': {source: 'res'}}
  ],
  http: {
    verb: 'get',
    path: '/download/:file'
  }
});
```

We should make streams a first-class citizen in strong-remoting.

`HttpContext.prototype.invoke` seems to already support piping a stream provided by the remotable method to the HTTP response ([source](https://github.com/strongloop/strong-remoting/blob/87ea65685ab9ff442b7769af5e4f24fdacd1fedb/lib/http-context.js#L217-L218)).

---

**Tasks**
 - [x] implementation in strong-remoting - see https://github.com/strongloop/strong-remoting/issues/35 and https://github.com/strongloop/strong-remoting/pull/284
 - [ ] support in loopback-swagger - see https://github.com/strongloop/loopback-swagger/issues/34
 - [ ] documentation - see https://github.com/strongloop/loopback/issues/2209

A note for loopback-swagger support. Swagger spec says: http://swagger.io/specification/#responseObject
> As an extension to the Schema Object, its root type value may also be "file". This SHOULD be accompanied by a relevant produces mime-type.

I don't remember whether loopback-swagger supports per-method `produces` option. If it does not, then we should implement it as part of this work.

Related: strongloop/loopback-component-explorer#103

**Comment by kuskov** [comment]
@bajtos i tried right now to use your solution but get following error:
```
{"error":{"name":"TypeError","status":500,"message":"Cannot read property 'apply' of undefined","stack":"TypeError: Cannot read property 'apply' of undefined\n    at SharedMethod.invoke (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:207:24)\n    at HttpContext.invoke (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:335:12)\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:608:11\n    at execStack (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:448:7)\n    at RemoteObjects.execHooks (/Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:452:10)\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:605:10\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/lib/application.js:330:13\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/lib/model.js:313:7\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/loopback/common/models/acl.js:465:23\n    at /Users/edgarkuskov/Documents/Foodo Workspace/foodo-api-server/node_modules/async/lib/async.js:251:17"}}
```

My code is:
```
 Order.download = function (file, res, cb) {
    var reader = fs.createReadStream(__dirname+'/../../storage/README.md');
    reader.on('error', function (err) {
      res.type('application/json');
      res.send(500, { error: err });
    });
    reader.pipe(res);
  };

  Order.remoteMethod('downloadPdf', {
    accepts: [
      {arg: 'orderId', type: 'string', 'http': {source: 'path'}},
      {arg: 'res', type: 'object', 'http': {source: 'res'}}
    ],
    http: {
      verb: 'get',
      path: '/downloadPdf/:orderId'
    }
  });
```

**Comment by tchambard** [comment]
Hi, I followed your server side implementation example to implement my own streaming from mongoDb gridfs storage, but I would be very interesting by the client side solution.
What I do not understand is how to pass the http response object as second argument...
I'm using Angular SDK and lbServices... but even with $http, I don't know how to do it...
Thanks for your help.

**Comment by tchambard** [comment]
I found the issue for my concern...
I needed to use res.send(500).send({ error: err }) instead of res.send(500, { error: err });

**Comment by benawarez** [comment]
Could you share how you implemented gridfs storage?  Thanks.

**Comment by bajtos** [comment]
Closing in favour of follow-up issues: https://github.com/strongloop/loopback-swagger/issues/34 and https://github.com/strongloop/loopback/issues/2209

**Comment by web-hollywood** [comment]
Hi bajtos

I'm currently trying to download a file from the backend API(loopback3).
So I integrated it like this.

UserProfile.remoteMethod (
    'totalDeductions',
    {
      description: 'Total deductions for exporting',
      accepts: [
        {arg: 'sDate', type: 'date', description: 'Start date for the report.', required: true},
        {arg: 'eDate', type: 'date', description: 'End date for the report.', required: true},
        {arg: 'res', type: 'object', 'http': {source: 'res'}}
      ],
      isStatic: true,
      returns: [
        { arg: 'body', type: 'file', root: true },
        { arg: 'Content-Type', type: 'string', http: { target: 'header' } },
        { arg: 'Content-Disposition', type: 'string', http: { target: 'header' } },
      ],
      http: {verb: 'get', path: '/total-deductions'}
    }
  );

UserProfile.totalDeductions = function(sDate, eDate, res, cb) {
    var DeductionModel = app.models.Deduction;
    var filter = {
      where: {
        dateCreated: {between: [sDate,eDate]}
      }
    };
    
    DeductionModel.find(filter, function(err, deductions) {
      var conf = {};
      conf.name = "mysheet";
      conf.cols = [{
        caption:'string',
            type:'string',
            beforeCellWrite:function(row, cellData){
           return cellData.toUpperCase();
        },
            width:28.7109375
      },{
        caption:'date',
        type:'date',
        beforeCellWrite:function(){
          var originDate = new Date(Date.UTC(1899,11,30));
          return function(row, cellData, eOpt){
                  if (eOpt.rowNum%2){
                    eOpt.styleIndex = 1;
                  }  
                  else{
                    eOpt.styleIndex = 2;
                  }
                    if (cellData === null){
                      eOpt.cellType = 'string';
                      return 'N/A';
                    } else
                      return (cellData - originDate) / (24 * 60 * 60 * 1000);
          } 
        }()
      },{
        caption:'bool',
        type:'bool'
      },{
        caption:'number',
         type:'number'        
      }];
      conf.rows = [
        ['pi', new Date(Date.UTC(2013, 4, 1)), true, 3.14],
        ["e", new Date(2012, 4, 1), false, 2.7182],
            ["M&M<>'", new Date(Date.UTC(2013, 6, 9)), false, 1.61803],
            ["null date", null, true, 1.414]  
        ];
      var result = nodeExcel.execute(conf);
      if (err) {
        cb(err);
        return;
      }
      var contentType =  'application/force-download';
      var contentDisposition = 'attachment; filename=xrt.pdf';
      cb(null, result,contentType, contentDisposition);
    });

But I'm not able to download a file. It still returns response as a contect, not a file.
Can you please help me?

**Comment by bajtos** [comment]
@web-hollywood I don't see any obvious problem. Please create a small app that I can use to reproduce the issue on my computer (see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) and open a new issue. Thanks!
