### ISSUE TITLE
EPIC: KeyValue models

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#2525]
### Problem

I should be able to easily read and write values in cache-friendly data stores. I should have control over exactly when each value expires. I should be able to choose my store.

### Example

```js
var wait = require('timer-as-promised');
var Color = app.createModel({
  base: 'KeyValueModel',
  keyValue: {
    ttl: {
      default: 120
    },
    namespace: 'colors'
  }
});
var redis = app.createDataSource('redis', {
  host: 'localhost',
  port: 6379
});
Color.attachTo(redis);

var SECONDS_TO_LIVE = 60;
var key = Math.random().toString().split('.')[1];
var myValue = new Color({
  key: key,
  value: 'blue',
});

myValue
  .setWithTTL(SECONDS_TO_LIVE)
  .then(function() {
    return myValue.ttl();
  })
  .then(function(ttl) {
    console.log(ttl); // 60
    return myValue.expire(120);
  })
  .then(function() {
    return wait(120);
  })
  .then(function() {
    return myValue.get();
  })
  .then(function() {
    console.log(myValue.value); // => undefined
  });
```

## Tasks
- [x] The first cut
- https://github.com/strongloop/loopback-datasource-juggler/pull/1023 (master)
- https://github.com/strongloop/loopback-datasource-juggler/pull/1031 (2.x)
- [x] Globalize the first cut
- https://github.com/strongloop/loopback-datasource-juggler/pull/1056
- https://github.com/strongloop/loopback-datasource-juggler/pull/1057
- [x] prototype methods (syntactic sugar)
- [x] `Color.ttl(key)` and `color.ttl()`
- https://github.com/strongloop/loopback-datasource-juggler/pull/1030
- https://github.com/strongloop/loopback-connector-kv-redis/pull/9
- [x] `Color.keys()` - https://github.com/strongloop/loopback/issues/2592
- [x] API docs - both in juggler and loopback
- https://github.com/strongloop/loopback/pull/2743
- https://github.com/strongloop/loopback-datasource-juggler/pull/1093
- [x] REST API in loopback repo - https://github.com/strongloop/loopback/pull/2594
- [x] KV memory connector example - https://github.com/strongloop-internal/scrum-loopback/issues/1017
- [x] Redis KV connector example - https://github.com/strongloop-internal/scrum-loopback/issues/1018
- [ ] Blog post on KV connectors - https://github.com/strongloop-internal/scrum-loopback/issues/1015

**Comment by bajtos** [comment]
@ritch I found few confusing parts of your example, could you please edit or clarify?

1) Where is the constructor `MyCacheItem` defined?
2) What's the difference between `myValue.setWithTTL()` and `myValue.expire()`?

We already have a redis connector ([link](https://github.com/strongloop/loopback-connector-redis)). I am worried about possible confusion - when to use `loopback-connector-redis` and `loopback-connector-kv-redis`.

I made a quick research, it seams to me that SQL servers don't provide key expiration, and on the other hand, Redis does not support advanced data-access methods like "updateOrCreate", so perhaps there should be only one connector for Redis, and it should implement the key/value API only (not DataAccessObject)?

Thoughts?

**Comment by raymondfeng** [comment]
Do you prefer static methods or prototype methods for KV operations? For example:

`MyKVModel.set(key, val, ttl, cb)` vs `MyKVModel.prototype.set(ttl, cb)`

Please note that we can use the model name as namespace for keys.

**Comment by superkhau** [comment]
Connect to #2545

**Comment by ritch** [comment]
> Please note that we can use the model name as namespace for keys.

We should do this. But I also like the idea of an object that represents the kv pair.

>  Where is the constructor MyCacheItem defined?

Typo, edited.

> What's the difference between myValue.setWithTTL() and myValue.expire()?

Atomic version of `set()` + `expire()` (`expire()` only sets the TTL)

> I made a quick research, it seams to me that SQL servers don't provide key expiration, and on the other hand, Redis does not support advanced data-access methods like "updateOrCreate", so perhaps there should be only one connector for Redis, and it should implement the key/value API only (not DataAccessObject)?

This is exactly the reason I am suggesting we create a key-value based set of connectors. The redis connector would probably be deprecated, since it doesn't really provide enough of the DAO connector interface to be interoperable anyway.

**Comment by superkhau** [comment]
>This in-memory implementation should be created as part of our work on key-value models.

I agree with this because we need an in-mem connector to write tests against.

**Comment by superkhau** [comment]
Example RI recommended by @raymondfeng: https://github.com/isaacs/node-lru-cache

**Comment by superkhau** [comment]
- Use it as the underlying module but expose our apis
  - Create our own in-mem connector that uses lru cache as the underlying module

**Comment by superkhau** [comment]
@bajtos I added a new bullet list item blog post for the feature + example. Also created corresponding issue at https://github.com/strongloop-internal/scrum-loopback/issues/1015.

**Comment by ritch** [comment]
@bajtos @superkhau - should we deprecate the redis connector in favor of this new redis kv connector?

**Comment by superkhau** [comment]
@ritch I'm not sure about this yet, there was one person using it recently in the PersistedModel fashion. I spoke with @raymondfeng about this before and we need a way to inject usage styles/templates to the connector at boot/runtimes to allow different usage styles for the same connector.

**Comment by superkhau** [comment]
Closing this issue in favour of leftover individual stories:

- https://github.com/strongloop/loopback/issues/2770
- https://github.com/strongloop-internal/scrum-loopback/issues/1074
- https://github.com/strongloop/loopback-connector-kv-redis/issues/15
- https://github.com/strongloop-internal/scrum-loopback/issues/1015
