### ISSUE TITLE
Key Value Redis Connector

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#2530]
Follow on for: https://github.com/strongloop/loopback/issues/2525

In order to use the proposed `KeyValueModel` you'll need a `key-value-connector`.

**loopback-connector-kv-redis**

This will implement the kv interface specified in https://github.com/strongloop/loopback/issues/2525 for redis.

/cc @raymondfeng @bajtos 

# Prerequisite

#2550

# Tasks

 - [x] project infrastructure (repository, README, etc.)
 - [x] core - connect to redis, implement `connector.execute`, `dataSource.ping`, test suite - https://github.com/strongloop/loopback-connector-kv-redis/pull/1 and
 - [x] KV API as defined in #2550 - https://github.com/strongloop/loopback-connector-kv-redis/pull/3
 - [x] lazyConnect - https://github.com/strongloop/loopback-connector-kv-redis/pull/2
 - [x] connection string/url
 - [x] globalization - https://github.com/strongloop/loopback-connector-kv-redis/pull/5

**Comment by superkhau** [comment]
Connect to #2545

**Comment by bajtos** [comment]
This has been done and released.
