### ISSUE TITLE
Models called "File" cause an error on POST

### ISSUE THREAD

**Issue by DaGaMs** [strongloop/loopback#2554]
I have a model called `File` and noticed a weird error when trying to POST to it:

```
{ error: 
   { name: 'Error',
     status: 500,
     message: 'Cannot create a file response from "object"',
     stack: 'Error: Cannot create a file response from "object"\n    at HttpContext.done ...
```

Renaming the model from `File` to `afile` or something like that fixes the issue. Here is a repo with a test case:

https://github.com/DaGaMs/loopback-file-bug-demo

It's really not ideal that loopback "clutters" the namespace for models like that. Both `User` and `Change` are reserved, and now it seems `File` is also a problem. It's a bit annoying to have to prefix my model names for that reason...

---

See https://github.com/strongloop/loopback/issues/2554#issuecomment-253786224 for the proposed solution.

**Tasks**
- [x] Fix the problem in strong-remotin@2.x - see https://github.com/strongloop/strong-remoting/pull/370
- [x] Start rejecting File/file custom types in strong-remoting@master - see https://github.com/strongloop/strong-remoting/pull/379
- [x] Update/create docs with a list of reserved type names - see https://github.com/strongloop/loopback.io/pull/148
- [x] Add a section to 3.0 Release Notes and Migration Guide - see https://github.com/strongloop/loopback.io/pull/148/

**Comment by gunjpan** [comment]
@DaGaMs : That's happening because every model method in LoopBack is a remote method and remote method allows a return type: [`file`](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Returningafile%28stream%29response) which is coincides with your return type of `File` for model: `File`.

I've labelled it as a bug and will bring it to the team's attention during our sprint planning.

@bajtos : I believe, we should enforce `reserved words` in LB. Thoughts? _(feel free to create a new issue and drive discussion there).

**Comment by bajtos** [comment]
The patch https://github.com/strongloop/strong-remoting/pull/370 provides a good short term fix, where we will distinguish between `type: 'file'` (a file stream) and `type: 'File'` (a model called `File`).

However, I feel this is rather confusing, because other types are case-insensitive, especially in LoopBack 3.x (the `TypeRegistry` always convert all types to lower-case, see https://github.com/strongloop/strong-remoting/blob/97507d26774cf81895ca7ee4a8e6623e166467b1/lib/type-registry.js#L33). I would like to fix this in longer term.

 - We can change the type system to be case-sensitive, i.e. `product` and `Product` are two different types. What are the downsides?
 - We can use different keywords for specifying strong-remoting primitives (`type: 'file'`) and complex objects (`model: 'File'`). This would be a breaking change though :(

What other options do we have?

@fabien @ritch @raymondfeng thoughts?

**Comment by fabien** [comment]
I think having a definite list of reserved keywords makes sense first of all. 

In addition, having an additional key within the `returns` spec would probably be a good alternative, for example: `as: 'file'` of ` file: true`. This would then signal the correct response logic, and the `type` key would more or less be ignored.

**Comment by bajtos** [comment]
On the second thought, I think we should add `file` to the list of reserved types and disallow developers to create models called `File`, starting with LoopBack 3.0. It is already not possible to create models like `Object` or `Number`, therefore I think it makes sense to extend this rule to `File` too.

I believe this will require the smallest amount of code changes and have the lowest maintenance costs in the future.

I am envisioning that we should register a new type converter for `file` type. Optionally, we can enhance `TypeRegistry` to reject re-definition of built-in types. Right now, we are emitting a warning whenever any type is redefined. The ability to redefine a user-defined type should be preserved, some of our downstream code is still depending on this feature.

**Comment by marcus-gomes-v** [comment]
> The patch [strongloop/strong-remoting#370](https://github.com/strongloop/strong-remoting/pull/370) provides a good short term fix, where we will distinguish between `type: 'file'` (a file stream) and `type: 'File'` (a model called `File`).
> 
> However, I feel this is rather confusing, because other types are case-insensitive, especially in LoopBack 3.x (the `TypeRegistry` always convert all types to lower-case, see https://github.com/strongloop/strong-remoting/blob/97507d26774cf81895ca7ee4a8e6623e166467b1/lib/type-registry.js#L33). I would like to fix this in longer term.
> 
> * We can change the type system to be case-sensitive, i.e. `product` and `Product` are two different types. What are the downsides?
> * We can use different keywords for specifying strong-remoting primitives (`type: 'file'`) and complex objects (`model: 'File'`). This would be a breaking change though :(
> 
> What other options do we have?
> 
> @fabien @ritch @raymondfeng thoughts?

Man your reply help me a lot, so many years after you reply, but Thanks!
