### ISSUE TITLE
EPIC: LoopBack connector support for pub/sub messaging

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2746]
As discussed with @raymondfeng @ritch, we should support pub/sub messaging styles in the LoopBack connector space.

At the moment, we only support [MQLight](https://github.com/strongloop/loopback-contributor-docs/blob/master/functional-area-owners.md#mq), but we should build in capabilities to allow extension for third party connectors such as MQTT.

---

List is WIP:
- [ ] Remoting API in LoopBack
- [ ] ChannelModel in Juggler
- [ ] Channel-memory connector in Juggler
- [ ] Try it all out by supporting one connector with we did with KV-redis (MQTT?)

Continue creating the todo list from KV connector tasks/PRs.

---

Example APIs suggested by @ritch:

```
var ds = loopback.createDataSource({
  connector: 'strong-pubsub-connector',
  adapter: 'mqtt',
  url: '...'
});

Channel.attachTo(ds);
```

```
// app a
var ch = new Channel('my-channel');
ch.publish('hello world');

// app b
var ch = new Channel('my-channel');
ch.on('msg', console.log); // => hello world
```

cc @bajtos

**Comment by bajtos** [comment]
I agree with the idea in general 👍 I have different opinion on implementation details though.

1)
I think the proposed API is not flexible enough. Many (if not all) messaging protocols allow clients to subscribe to multiple topics. When publishing a message, a single topic must be selected. When subscribing to messages, multiple topics can be specified, including a wildcard. I don't see how a `new Channel(topicName)` API can support this use case.

See e.g. the API in [strong-mq](https://github.com/strongloop/strong-mq/blob/master/api.md#subsubscribepattern-listener) and also their description of typical messaging scenarios ([link](https://github.com/strongloop/strong-mq/blob/master/api.md#message-patterns)):

> - work queue: published messages are delivered to a single subscriber, common when distributing work items that should be processed by a single worker
> - topic: published messages are delivered to all subscribers, each message is associated with a "topic", and subscribers can specify the topic patterns they want to receive
> - rpc: published messages are delivered to a single subscriber, and a associated response is returned to the original publisher

We should base the design our API on a good understanding of different scenarios where MQ is used, to make sure the API makes it easy to accomplish what our user needs.

2)
> ChannelModel in Juggler
> Channel-memory connector in Juggler

I feel juggler is not the right place for this new feature. I had the feeling already when implementing KeyValue models, but that one was at least still about persisting data, plus we were little bit in a rush to deliver the feature.

Now that we are going to implement another new concept, let's take the necessary time to figure out how to correctly structure our code.

For example, do we need `ChannelModel` base model at all? Can we put the code shared by all connectors into `loopback-connector` or `loopback-connector-mq` instead?

> Remoting API in LoopBack

I personally find it annoying that adding a new remote method in a connector requires changes in several repositories. Can we use the MQ feature as an opportunity to figure out how to keep all code related to a single remote connector method in a single place?

> Channel-memory connector

We may want to reuse bits from strong-mq in the implementation of the connector. (Just make sure to leave out the cross-cluster-worker sharing, that does not work in most deployment anyways.)
