### ISSUE TITLE
Tighten security for resetting password

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback#382]
With `POST /user/{id}` user can change password without of presence of old password. This is security problem, because anyone who stoles any valid access token from user can change users password.

**Tasks**
- [x] Only allow resetPassword by email if email verification is required and done.
- [x] #3303 - Provide solution for finishing the registration when the verification link was not followed (opened) before it has expired.
- [x] Add a new method, let's call it `User.changePassword(id, oldPassword, newPassword, cb)`. This method should have ACLs configured to allow only the owner to execute it (i.e. users can change only their own passwords) - see https://github.com/strongloop/loopback/pull/3299
- [x] Scope the password-reset token so that it allows only changing User's password and nothing else. Regular access tokens must not allow changing User's password without providing the old one. 
  ~~Save the password-reset token the same way as the verification token i.e. with the user. That way you would know with which token you can change the password without knowing your old one. It would also mean that if you request another password reset it would delete/invalidate the previous token so that at max only one can be active at one time. Because the current implementation relies on the client to call `updateAttributes` with a temporary access token, I think we will need to implement a new method similar to `User.changePassword` that will accept the new reset-token instead of the old password.~~
  - [x] https://github.com/strongloop/loopback/pull/3313 Implement Access Token Scopes
  - [x] #3350 - Implement a new method for resetting the password. This method does not require the old password and can be invoked only with a password-reset token
- [x] #3350 - Disable changing the `password` property via other methods. To preserve backwards-compatibility, there should be a feature flag controlling this behaviour.

**Next**
- https://github.com/strongloop/loopback/issues/3349

**Comment by shaunbruno** [comment]
Reading the comments, I realize this issue was closed as there may have been no further discussion. As @offlinehacker  and @TFaga have noted, a scope/type concept to differentiate the reset password token from a normal token would solve the issue.

Having read the code in my current version (see version info below), if I'm not mistaken the normal reset password scenario (without being logged in) has a fairly significant security flaw insofar that the AccessToken generated provides system wide access for 15 minute (simply by providing a valid email). 

The counter argument is perhaps that if the requester also has the email then they are indeed the owning user? If so, I would disagree and +1 expediting the differentiation of the AccessToken's type (so that a reset password user does not have the same full-access permissions as a normal user).

Version Info:
strongloop v2.10.3 (node v0.10.32)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── node-inspector@0.7.4
├── strong-deploy@1.1.4 (5e25e21)
├── strong-pm@1.7.2 (315d448)
├── strong-registry@1.1.4 (aab3dbb)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.1 (f9f97e5)

**Comment by raymondfeng** [comment]
+1 to add `scopes` to AccessToken model. We have a TODO to fully consolidate the oAuth2 related models with the base User/Application/AccessToken/Scope models.

**Comment by raymondfeng** [comment]
The other thing is that we should only allow resetPassword by email if email verification is required and done.

**Comment by ritch** [comment]
> +1 to add scopes to AccessToken model.

Agreed. We need support for scopes in ACLs first though. @raymondfeng can you link that issue here (or PR)?

> The other thing is that we should only allow resetPassword by email if email verification is required and done.

Yep.

**Comment by ritch** [comment]
> Another idea would be to save it the same way as the verification token i.e. with the user. That way you would know with which token you can change the password without knowing your old one. It would also mean that if you request another password reset it would delete/invalidate the previous token so that at max only one can be active at one time.

I like this idea actually... It means we must somehow tag the token though. @raymondfeng would this be possible using your scope implementation?

**Comment by raymondfeng** [comment]
There are two things involved:

1. How to make sure there is only one active token in place per user for e-mail verification or password reset?
2. How to prevent the special tokens from being used out of scope?

For 1, we need to ensure the integrity during verify/resetPassword.
For 2, we need to add scopes to the access token.

**Comment by shaunbruno** [comment]
@raymondfeng For (1) there are a couple options - of course as mentioned the reset token could be included as a (typically null - when not in use) property on the User model. Alternatively, I used for a personal implementation a separate ResetPasswordToken model with a 1-1 correspondence to it's owning User model. The second strategy affords additional tracking on the reset process (global number of resets, last reset time, etc.)

Either is a reasonable framework strategy, but wanted to share for collaboration.

**Comment by johnsoftek** [comment]
Reset password is the only way at present to continue an incomplete
registration (where the verification link is not followed before expiry),
so don't close it off without some other work around.

**Comment by bajtos** [comment]
Based on the discussion above, I am proposing the following changes as the immediate fix of the issue:

1) Only allow resetPassword by email if email verification is required and done.

2) Save the password-reset token the same way as the verification token i.e. with the user. That way you would know with which token you can change the password without knowing your old one. It would also mean that if you request another password reset it would delete/invalidate the previous token so that at max only one can be active at one time. 

3) Provide solution for finishing the registration when the verification link was not followed (opened) before it has expired.

> add scopes to AccessToken model. We have a TODO to fully consolidate the oAuth2 related models with the base User/Application/AccessToken/Scope models.

Since this TODO item hasn't make it to our sprint backlog in more than a year, I would rather not wait for it and start implementing the solution described above, even if it may not be ideal.

**Comment by bajtos** [comment]
As I was re-reading the discussion above, I think the proposal in my https://github.com/strongloop/loopback/issues/382#issuecomment-224954978 does not cover the most important aspect of the original issue:

> With `POST /user/{id}` user can change password without of presence of old password. This is security problem, because anyone who stoles any valid access token from user can change users password.

To fix that, I think we should also

4) Add a new method, let's call it `User.changePassword(id, oldPassword, newPassword, cb)`. This method should have ACLs configured to allow only the owner to execute it (i.e. users can change only their own passwords).

5) Disable changing the `password` property via other methods. To preserve backwards-compatibility, there should be a feature flag controlling this behaviour.

**Comment by lazaridis-com** [comment]
@raymondfeng , @bajtos - I try to understand why a security-related issue is kept for 2,5 years open. Shouldn't this been a high priority issue, fixed immediately?

**Comment by bajtos** [comment]
Hello everybody subscribed to this thread/issue. I have good news for you - I am going to work on the proposed changes in the next two weeks.

My first step:  https://github.com/strongloop/loopback/pull/3299 adding `User.changePassword()`.

**Comment by johnsoftek** [comment]
@bajitos It seems a good idea to add a facility to change password when the old password is known - as proposed using User.changePassword. This should not require email verification. I am fairly sure that the emailVerificationRequired setting is meant for registration, not password changes.

However, change known password is different from a password reset, which is a facility to change password when the old password is lost or forgotten. Password reset usually requires an alternative confirmation of account ownership, for example access to an email account, mobile phone or answering pre-registered security questions.

**Comment by bajtos** [comment]
> Save the password-reset token the same way as the verification token i.e. with the user. That way you would know with which token you can change the password without knowing your old one. 

On the second thought, I think we should not follow this proposal of mine. When the `User` model contains has sensitive auth-related properties like hashed "password" or password reset token, then it's difficult to perform a full replace (`replaceById` at `PUT /api/users/:id`) - either the client has to know all sensitive auth properties (which is a security vulnerability), or the client cannot make the full replace at all.

I think we should move all sensitive information into different models (e.g. `UserPassword` model for the password). This will make it easier to implement the task "Disable changing the password property via other methods. " too.

@raymondfeng @ebarault thoughts?

The tricky part is how to make this configurable, so that existing applications can keep using `User.password`, while new apps start using `User` and `UserPassword` models. I am sure a solution can be found for that.

**Comment by bajtos** [comment]
@johnsoftek thanks for chiming in!

> It seems a good idea to add a facility to change password when the old password is known - as proposed using User.changePassword. This should not require email verification. I am fairly sure that the emailVerificationRequired setting is meant for registration, not password changes.

The currently proposed implementation of `changePassword` does not check whether the email is verified or not. However, notice that if `emailVerificationRequired` is enabled, then a verified email is required for login - this is an existing functionality.

> However, change known password is different from a password reset, which is a facility to change password when the old password is lost or forgotten. Password reset usually requires an alternative confirmation of account ownership, for example access to an email account, mobile phone or answering pre-registered security questions.

Agreed.

**Comment by ebarault** [comment]
hi all, you can follow and participate to the discussion on 
**Provide solution for finishing the registration when the verification link was not followed (opened) before it has expired.** in #3303

**Comment by bajtos** [comment]
All tasks listed in the issue in the issue description were landed and released in `loopback@3.7.0`. I am going to close this issue as resolved. See #3349 for the issue/task tracking update of documentation, examples and project templates. Help is welcome!
