### ISSUE TITLE
Leftovers from 2.0

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#391]
List of leftovers from #276.

- [ ] trackChanges should be well documented (remove from `Model`)
- [ ] remove [global modelBuilder](https://github.com/strongloop/loopback/blob/2.0/lib/loopback.js#L128)
- ~~remove `loopback.createModel()` in favor of `Model.extend()`~~
- [x] rename `DataModel` to `PersistedModel`
- [x] [remove unused explorer](https://github.com/strongloop/loopback/pull/272#discussion-diff-12943976R6) - see https://github.com/strongloop/loopback/pull/392
- [ ] remove `DataModel` mixins in favor of simple delegation
- [ ] `DataModel` methods should delegate to the dataSource directly
- [ ] refactor `DataModel#replicate()` into `Replication` class.
- [ ] refactor `DataModel#bulkUpdate()` into `BulkUpdate` class.
- [ ] refactor `DataModel#diff()` into `Diff` class.
- ~~remove `Model` autoAttach~~
- [ ] [password should be validatable](https://github.com/strongloop/loopback/issues/251)
- [ ] docs for any class should include any available method (eg. inherited / mixed-in / etc)
- [ ] tests should not share any objects (eg. create a new app / modelBuilder for all tests)
- [x] karma tests should run in ci
- [ ] beef up CHANGES.md
- [x] create upgrade guide 1.x => 2.x
- [ ] remove `app.remoteObjects()`
- [x] [move memory connector filtering into its own module](https://github.com/strongloop/loopback-filter)
- [ ] rename `ACL` => `AccessControl` and `options.acls` to `options.acl`.
- [ ] remove `sharedCtor` and remoted prototype methods (probably not - see https://github.com/strongloop/strong-remoting/issues/73)
- [ ] document model.settings.remoting / remoting options
- [ ] document base URL setting for models
- [ ] all URLs should be lowercase / dasherized (both configurable)
- [ ] groundwork for allowing ACL to provide route names
- [ ] groundwork for allowing non-model remote classes (eg. Resource and/or Controller)
- [ ] groundwork for supporting promises via remoting
- [ ] groundwork for supporting promises for `DataModel` methods
- [x] migrate `app.boot()` into its own separate module
- [ ] migrate `ACL` into its own separate module
- [ ] groundwork for removing remoting metadata from JS
- [x] groundwork for removing juggler as a dependency (#275)
- [ ] remove or properly impelment "property" from ACL

List of issues assigned to 2.0 milestone but not implemented in 2.0:

 - [ ] #360
 - [ ] #346
 - [x] #345
 - [ ] #343
 - [ ] #305
 - [ ] #278
 - [x] #275
 - [x] #209
 - [x] #194
 - [x] #169
 - [ ] #157
 - [ ] #148
 - [ ] #126
 - [ ] #114
 - [ ] #109
 - [ ] #80

**Comment by crandmck** [comment]
I don't believe this should have the "doc" label; although some of the items are doc items, many are not.  If and when we create specific doc issues from the items on the list, then those should have the "doc" label.

**Comment by bajtos** [comment]
> I don't believe this should have the "doc" label; although some of the items are doc items, many are not. If and when we create specific doc issues from the items on the list, then those should have the "doc" label.

Agreed :+1:

**Comment by bajtos** [comment]
Considering that this issue is over 18 months old and the issues in the list were not important enough to fix them so far, I doubt we will ever work on them. I am closing this issue.
