### ISSUE TITLE
Describe properties and models in LDL

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#638]
1. I am proposing to use `description` to document a property and and model defined in LDL. This is consistent with `description` field used in remoting metadata.
2. The `description` value can be either a simple string, or an array of strings. The latter is interpreted as a list of lines (i.e. the single string value is produced by joining all items with a new-line character) and it allows developers to write longer description while keeping the line length below 80 chars.
3. Remoting metadata should support "array of strings" values too.

Example:

``` json
{
  "name": "MyModel",
  "description": "A model with a description.",
  "properties": {
    "production": {
      "type": "boolean",
      "description": [
        "Production or development mode. It denotes what default APNS",
        "servers to be used to send notifications.",
        "See API documentation for more details."
      ]
    }
  }
}
```

**Tasks**
- [x] Update [Model definition JSON file](http://docs.strongloop.com/display/LB/Model+definition+JSON+file)
- [x] Modify loopback-explorer to support array values of `description`. Possibly support array values for other fields like `notes` too.
- [x] Update [Definiton remote methods](http://docs.strongloop.com/display/LB/Defining+remote+methods)

/to @ritch @raymondfeng @fabien thoughts?
/cc @superkhau @altsang
