### ISSUE TITLE
Request handling phases

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#739]
Now that we have `loopback-phase`, we should put it to use in loopback core and simplify the task of registering middleware in the correct order.

See https://github.com/strongloop/loopback-boot/issues/46 for background discussion.

**Tasks**
- [x] Implement a prototype of PhasedRouter in LoopBack - see #757
- [x] Get the prototype reviewed, decide whether it should be moved
  to a standalone project (e.g. strong-router).
- [x] Finish the prototype, make it production-ready - see #767 
- [x] Add more predefined phases - see #767
- [x] Add API for adding custom phases - see #786
- [x] Clean up the implementation - see #792, #790 and strongloop/loopback-phase#7
- [x] cleanup round 2 - #796
- [x] Write down a draft of the documentation - see https://github.com/strongloop/loopback/issues/863 and https://gist.github.com/bajtos/e7eaba736ff096916b71

**Related**
- https://github.com/strongloop/loopback-boot/issues/44 Middleware Mounting in loopback-boot
