### ISSUE TITLE
Reduce the size of loopback client bundle

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#989]
At the moment, a browserified loopback module has about 1.4MB uncompressed, 650KB compressed. This size is unacceptable, especially for mobile browsers on a slow internet connection. We need to get at least below 100kb.

This GH issue is a time-scoped story. The goal is to analyse the dependencies, fix as many low-hanging fruits as possible and then create follow-up stories for the unsolved items.

Subtasks:
- [x] strongloop/loopback-datasource-juggler#538 - remove lodash
- [x] strongloop/strong-remoting#187 - remove js2xmlparser and cors
- [x] #1246 - optimise underscode.string usage
- [ ] #1247 - rework places using crypto module
- [ ] #1249 - don't use bcryptjs in browser
- [x] strongloop/strong-remoting#177 - use a smaller HTTP client in the browser
- [ ] https://github.com/strongloop/loopback/issues/1211 - pluggable HTTP client
- [ ] Investigate if we can get rid of "buffer" usage in the browser

**Comment by BerkeleyTrue** [comment]
@bajtos any advice or strategies on this?

**Comment by bajtos** [comment]
My plan is to produce profiling data using file (bundle) size instead of execution time, so that we can identify the files and modules that contribute most to the overall size. There may be an existing browserify module for that, I did not check yet. (Please let me know if you figure out how to do this.)

Once we have that information, it should be easy to pick the biggest dependencies, check if they are used by the browser client, and exclude them using `browser` field in the relevant package.json field if they are not needed.

**Comment by BerkeleyTrue** [comment]
So the first step is to get the size of each file/script in the bunde?

**Comment by bajtos** [comment]
For each file/script, you need two values: the size of the file itself, and the cumulated size of all dependencies including the file itself.

For example, a single-line file `var loopback = require('loopback')` is small itself (about 20 bytes), but huge when dependencies are included (1.4MB).

**Comment by bajtos** [comment]
I did some investigation in the past two days while I was travelling.

The biggest contributor to the bundle size is the "crypto" module, it adds ~650kb unminified. See https://github.com/strongloop/loopback/issues/1247 for a follow-up discussion.

Another big dependency is lodash with 367kb unminified. https://github.com/strongloop/loopback-datasource-juggler/pull/538 removes this dependency.

Smaller modules that were easy to remove:

 - Use only the relevant subset of "underscore.string" - https://github.com/strongloop/loopback/pull/1246 saves about 25kb.
 - Don't use `js2xmlparser` and `cors` in the browser - https://github.com/strongloop/strong-remoting/pull/187 saves about 14kb

Other things to do:

 - "bcryptjs" has about 50kb un-minified. The method is used by `User.hasPassword` and `User.hashPassword`. Discussion: https://github.com/strongloop/loopback/issues/1249

 - Refactor loopback-datasource-juggler and loopback too achieve higher code reuse and less duplication. This is a tricky thing, I don't know if we want to go down this route unless absolutely necessary.

  * juggler lib/relation-definition.js: 86kb
  * juggler lib/datasource.js: 61kb
  * juggler lib/dao.js: 60kb
  * loopback lib/persisted-model: 47kb

Things I found but don't know whether they can be fixed:

 - browserify's readable-stream has 55kb, it's needed by crypto-browserify and http-browserify. Perhaps if we can rework the remoting adapter to use http API that is closer to the browser, then we could get rid of this dependency. See https://github.com/strongloop/strong-remoting/issues/177.

 - browserify's buffer has 43kb (about 5kb minified). It's used by at least in these places:  crypto-browserify, readable-stream, strong-remoting/lib/shared-method.js, common/models/access-token.js, loopback-datasource-juggler/lib/types.js

**Comment by BerkeleyTrue** [comment]
Found this last night https://github.com/hughsk/disc. it visualise the size of scripts in a bundle. Was going to investigate how it generates this data but I see you beat me to it. Though I share it anyway.

**Comment by bajtos** [comment]
> Found this last night https://github.com/hughsk/disc. it visualise the size of scripts in a bundle. Was going to investigate how it generates this data but I see you beat me to it. Though I share it anyway.

Thank you for sharing this! I hacked browserify to report dependent-dependency edges and then wrote a simple analytics script to give me some insights, because that's was the easiest option while being offline. However, the disc module looks very useful, I'll give it a try someday.

**Comment by malte-wessel** [comment]
+1

**Comment by mattaylor** [comment]
+1

**Comment by mattaylor** [comment]
Any movement here? This issue really renders offline / isomorphic usecases for loopback unworkable in production

**Comment by LucaColonnello** [comment]
+1

**Comment by jantimon** [comment]
"This issue really renders offline / isomorphic usecases for loopback unworkable in production"
We decided not to use loopback / strongloop just because this issue.
People are complaining that said they don't want to use jQuery because of the 35kb so imho a rest library with 2-5 models should not consume more than 20kb gziped.

Maybe you should provide another entry point with has just the client network stack and model definitions instead of browserifying tons and tons of server code.

**Comment by ritch** [comment]
> Maybe you should provide another entry point with has just the client network stack and model definitions instead of browserifying tons and tons of server code.

+1 for this

Its really not as out of reach as it might sound. I think @bajtos has mentioned some of the steps to do this.

This is what I'd like to see:

 - a build script (eg. a gulp file) included with the boilerplate of loopback (output of `slc loopback`)
 - outputs a browser version of your client directory
 - the build will exclude and shim modules to make the bundle a reasonable size
 - only includes modules required by your configuration (also in the build script).
   - eg.`hasPassword()` will not be supported and its deps will be shimmed with empty modules
 - allowing you to opt into features that require significantly larger modules

**Comment by acao** [comment]
This is great!

One of the biggest issues though, it seems, is compacting the size of the datasource juggler. This and loopback seemed to be the largest modules in the bundle.

I'm with @Jantimon. I've used pouchdb before and it's great and achieves a lot for a small library. We could probably come up with a thin client ODM that works like loopback datasource juggler without necessitating all the cruft of loopback itself. Like he was suggesting, on client boot it would request a payload of model definitions, learn about additional REST endpoints, etc. Then there could be simplified loopback-connectors for localstorage, pouchdb, linvodb3, etc for client-focused implementations.

Generally, the real need becomes a much greater modularization of looback and the datasource juggler if you plan on continuing to bundle any of this together for the browser, especially with optional modules.  Currently it appears to be all or nothing.

Another idea is this - what if we were to build a library that could be used to inflect the logic of the loopback ODM into customized generators, as defined by your application? So you could create generators for angular $resource, ember data, for superagent and/or for flux implementations, all from the same logic.

**Comment by TonyLuo** [comment]
+1.  I only use some models  . Is any way to define which models should be generated and which should not be generated in the  AngularJS client file?

**Comment by bajtos** [comment]
> +1. I only use some models . Is any way to define which models should be generated and which should not be generated in the AngularJS client file?

This issue (#989) is discussing the size of the client bundle produced by browserify. 

Please open a new issue in [loopback-sdk-angular](https://github.com/strongloop/loopback-sdk-angular/issues/new) to discuss feature requests for the AngularJS client code generator.
